SELECT * FROM EMPLOYEE

SELECT * FROM DEPARTMENT

SELECT * FROM LOCATION

SELECT * FROM JOB

SELECT empid,name
FROM Employee
WHERE managerid = 986

SELECT DISTINCT(project)
FROM Salary

SELECT COUNT(*) 
FROM Salary
WHERE project='P1'

SELECT MAX(Salary), MIN(Salary), AVG(Salary)
FROM Salary

SELECT project 
FROM Salary 
WHERE Salary BETWEEN 30000 AND 40000;

SELECT empid,name,managerid,doj,city
FROM Employee
WHERE city = 'Chennai' AND managerid=986

SELECT empid 
FROM Salary
WHERE NOT project='P1'

SELECT empid,salary+variable As Totalsalary 
FROM Salary
ORDER BY empid DESC

SELECT empid,name
FROM Employee
WHERE name LIKE '%vi%'


SELECT * FROM EMPLOYEE
WHERE comm IS NULL

SELECT * FROM EMPLOYEE
WHERE employee_id=10 AND salary>3500

SELECT employee_id,last_name,salary
FROM EMPLOYEE
ORDER BY salary DESC

SELECT department_id, COUNT(employee_id)
FROM EMPLOYEE
GROUP BY department_id;

SELECT department_id,COUNT(employee_id)
FROM EMPLOYEE
GROUP BY department_id HAVING COUNT(employee_id)>=3

SELECT  MAX(salary)FROM EMPLOYEE

SELECT * FROM EMPLOYEE 
WHERE salary=(SELECT MAX(salary)FROM EMPLOYEE)

SELECT * FROM EMPLOYEE
left JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
WHERE DEPARTMENT.name = 'SALES'

SELECT *FROM DEPARTMENT
JOIN LOCATION
on DEPARTMENT.DEPARTMENT_ID=LOCATION.LOCATION_ID
WHERE name='NEW YORK'

SELECT *FROM EMPLOYEE
left JOIN DEPARTMENT
ON EMPLOYEE.EMPLOYEE_ID=DEPARTMENT.DEPARTMENT_ID
DELETE DEPARTMENT
WHERE NAME='ACCOUNTING'


SELECT * FROM EMPLOYEE
JOIN JOB
ON EMPLOYEE.JOB_ID=JOB.JOB_ID;
UPDATE EMPLOYEE
SET salary = salary * 2 




